import pygame
pygame.mixer.pre_init(44100, -16, 1, 512)
pygame.init()
step_sound = pygame.mixer.Sound("sounds/step_sound.ogg")
step_sound.set_volume(0.3)
sword_sound = pygame.mixer.Sound("sounds/miss.ogg")
sword_sound.set_volume(0.4)
sword_hit = pygame.mixer.Sound("sounds/sword_hit.ogg")
sword_hit.set_volume(0.2)
bow_shoot = pygame.mixer.Sound("sounds/bow_shoot.wav")
bow_shoot.set_volume(0.075)
bow_hit = pygame.mixer.Sound("sounds/bow_hit.wav")
bow_hit.set_volume(0.3)
ram_sound = pygame.mixer.Sound("sounds/ram_sound1.wav")
ram_sound.set_volume(0.2)